# theme: minima
remote_theme: jekyll/minima

author:
  name: Pavel Kulmon
  email: "kulmon@seznam.cz"

description: >
  Special repository with support material for our MFI 2024 keynote.

minima:
  skin: dark

header_pages:
  - people.md
  - era.md